/* Additional record code for FmuExportCrossCompile generated by the OpenModelica Compiler OMCompiler v1.12.0-dev.131+gc80769b. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

