/* Simulation code for RoomHeating_OM.RH generated by the OpenModelica Compiler OMCompiler v1.12.0-dev.131+gc80769b. */
#if !defined(RoomHeating_OM_RH__MODEL_H)
#define RoomHeating_OM_RH__MODEL_H
#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <string.h>

#include "RoomHeating_OM_RH_functions.h"


extern void RoomHeating_OM_RH_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void RoomHeating_OM_RH_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int RoomHeating_OM_RH_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int RoomHeating_OM_RH_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int RoomHeating_OM_RH_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int RoomHeating_OM_RH_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int RoomHeating_OM_RH_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int RoomHeating_OM_RH_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int RoomHeating_OM_RH_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int RoomHeating_OM_RH_checkForAsserts(DATA *data, threadData_t *threadData);
extern int RoomHeating_OM_RH_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int RoomHeating_OM_RH_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int RoomHeating_OM_RH_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern int RoomHeating_OM_RH_checkForDiscreteChanges(DATA *data, threadData_t *threadData);
extern const char* RoomHeating_OM_RH_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* RoomHeating_OM_RH_relationDescription(int i);
extern void RoomHeating_OM_RH_function_initSample(DATA *data, threadData_t *threadData);
extern int RoomHeating_OM_RH_initialAnalyticJacobianG(void* data, threadData_t *threadData);
extern int RoomHeating_OM_RH_initialAnalyticJacobianA(void* data, threadData_t *threadData);
extern int RoomHeating_OM_RH_initialAnalyticJacobianB(void* data, threadData_t *threadData);
extern int RoomHeating_OM_RH_initialAnalyticJacobianC(void* data, threadData_t *threadData);
extern int RoomHeating_OM_RH_initialAnalyticJacobianD(void* data, threadData_t *threadData);
extern int RoomHeating_OM_RH_functionJacG_column(void* data, threadData_t *threadData);
extern int RoomHeating_OM_RH_functionJacA_column(void* data, threadData_t *threadData);
extern int RoomHeating_OM_RH_functionJacB_column(void* data, threadData_t *threadData);
extern int RoomHeating_OM_RH_functionJacC_column(void* data, threadData_t *threadData);
extern int RoomHeating_OM_RH_functionJacD_column(void* data, threadData_t *threadData);
extern const char* RoomHeating_OM_RH_linear_model_frame(void);
extern const char* RoomHeating_OM_RH_linear_model_datarecovery_frame(void);
extern int RoomHeating_OM_RH_mayer(DATA* data, modelica_real** res, short *);
extern int RoomHeating_OM_RH_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int RoomHeating_OM_RH_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int RoomHeating_OM_RH_setInputData(DATA *data, const modelica_boolean file);
extern int RoomHeating_OM_RH_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void RoomHeating_OM_RH_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void RoomHeating_OM_RH_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int RoomHeating_OM_RH_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void RoomHeating_OM_RH_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void RoomHeating_OM_RH_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int RoomHeating_OM_RH_inputNames(DATA* data, char ** names);
extern int RoomHeating_OM_RH_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int RoomHeating_OM_RH_functionLocalKnownVars(DATA*, threadData_t*);

#include "RoomHeating_OM_RH_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#endif


